# Generated by Django 4.0.3 on 2022-04-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trialNumber', models.PositiveIntegerField()),
                ('starttime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_condition', models.CharField(choices=[('rainy', 'rainy'), ('foggy', 'foggy'), ('Sunny', 'Sunny'), ('cloudy', 'cloudy'), ('Snow', 'Snow'), ('night', 'night'), ('forest', 'forest')], max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tempdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=51)),
                ('count', models.IntegerField(default=-1)),
                ('trialNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.PositiveIntegerField()),
                ('break1', models.CharField(blank=True, max_length=51, null=True)),
                ('break2', models.CharField(blank=True, max_length=51, null=True)),
                ('break3', models.CharField(blank=True, max_length=51, null=True)),
                ('break4', models.CharField(blank=True, max_length=51, null=True)),
                ('break5', models.CharField(blank=True, max_length=51, null=True)),
                ('break6', models.CharField(blank=True, max_length=51, null=True)),
                ('break7', models.CharField(blank=True, max_length=51, null=True)),
                ('break8', models.CharField(blank=True, max_length=51, null=True)),
                ('break9', models.CharField(blank=True, max_length=51, null=True)),
                ('break10', models.CharField(blank=True, max_length=51, null=True)),
                ('break11', models.CharField(blank=True, max_length=51, null=True)),
                ('break12', models.CharField(blank=True, max_length=51, null=True)),
                ('result', models.CharField(choices=[('speedbreaker', 'speedbreaker'), ('normal', 'normal'), ('rough_surface', 'rough_surface'), ('Descend', 'Descend'), ('ascend', 'ascend'), ('obstacle', 'obstacle')], max_length=128)),
                ('time', models.DateTimeField()),
                ('weather_condition', models.CharField(blank=True, choices=[('rainy', 'rainy'), ('foggy', 'foggy'), ('Sunny', 'Sunny'), ('cloudy', 'cloudy'), ('Snow', 'Snow'), ('night', 'night'), ('forest', 'forest')], max_length=128, null=True)),
                ('placeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.location')),
                ('vehicleName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chances', models.PositiveIntegerField(blank=True, null=True)),
                ('final_result', models.CharField(choices=[('speedbreaker', 'speedbreaker'), ('normal', 'normal'), ('rough_surface', 'rough_surface'), ('Descend', 'Descend'), ('ascend', 'ascend'), ('obstacle', 'obstacle')], max_length=128)),
                ('placeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.location')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='placeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.location'),
        ),
        migrations.AddField(
            model_name='entity',
            name='vehicleName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.vehicle'),
        ),
    ]
