# Generated by Django 4.0.3 on 2022-03-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.PositiveIntegerField()),
                ('break1', models.IntegerField(blank=True, null=True)),
                ('break2', models.IntegerField(blank=True, null=True)),
                ('break3', models.IntegerField(blank=True, null=True)),
                ('break4', models.IntegerField(blank=True, null=True)),
                ('break5', models.IntegerField(blank=True, null=True)),
                ('break6', models.IntegerField(blank=True, null=True)),
                ('break7', models.IntegerField(blank=True, null=True)),
                ('break8', models.IntegerField(blank=True, null=True)),
                ('break9', models.IntegerField(blank=True, null=True)),
                ('break10', models.IntegerField(blank=True, null=True)),
                ('break11', models.IntegerField(blank=True, null=True)),
                ('break12', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('speedbreaker', 'speedbreaker'), ('normal', 'normal'), ('rough_surface', 'rough_surface'), ('Descend', 'Descend'), ('ascend', 'ascend'), ('obstacle', 'obstacle')], max_length=128)),
                ('time', models.DateTimeField()),
                ('weather_condition', models.CharField(choices=[('rainy', 'rainy'), ('foggy', 'foggy'), ('Sunny', 'Sunny'), ('cloudy', 'cloudy'), ('Snow', 'Snow'), ('night', 'night'), ('forest', 'forest')], max_length=128)),
                ('placeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.location')),
                ('vehicleName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chances', models.PositiveIntegerField(blank=True, null=True)),
                ('final_result', models.CharField(choices=[('speedbreaker', 'speedbreaker'), ('normal', 'normal'), ('rough_surface', 'rough_surface'), ('Descend', 'Descend'), ('ascend', 'ascend'), ('obstacle', 'obstacle')], max_length=128)),
                ('placeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showdata.location')),
            ],
        ),
    ]
