# Generated by Django 4.0.3 on 2022-03-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='weather_condition',
            field=models.CharField(blank=True, choices=[('rainy', 'rainy'), ('foggy', 'foggy'), ('Sunny', 'Sunny'), ('cloudy', 'cloudy'), ('Snow', 'Snow'), ('night', 'night'), ('forest', 'forest')], max_length=128, null=True),
        ),
    ]
