# Generated by Django 4.0.3 on 2022-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdata',
            name='trialNumber',
        ),
        migrations.AddField(
            model_name='entity',
            name='data',
            field=models.ManyToManyField(to='showdata.tempdata'),
        ),
    ]
