# Generated by Django 4.0.3 on 2022-04-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0002_location_is_active_vehicle_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_condition', models.CharField(choices=[('rainy', 'rainy'), ('foggy', 'foggy'), ('Sunny', 'Sunny'), ('cloudy', 'cloudy'), ('Snow', 'Snow'), ('night', 'night'), ('forest', 'forest')], max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
