# Generated by Django 4.0.3 on 2022-04-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0003_entity_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='trialNumber',
        ),
    ]
