# Generated by Django 4.0.3 on 2022-04-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0004_remove_entity_trialnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='break1',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break10',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break11',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break12',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break2',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break3',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break4',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break5',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break6',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break7',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break8',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='break9',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='fluctuation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='final',
            name='chances',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='total_time',
            field=models.DurationField(),
        ),
    ]
