# Generated by Django 4.0.3 on 2022-04-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0005_remove_rawdata_break1_remove_rawdata_break10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='fluctuation',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
